// This file ensures UnoCSS is properly loaded in Next.js

export default function loadUnoCSS() {
  // This function is a placeholder for UnoCSS integration
  // The actual CSS is generated by the UnoCSS CLI and imported in globals.css
  return true
}